CREATE TABLE "PM_DATA_USER"."PM_DATA_CONFIG" 
   (	"SCHEMA" VARCHAR2(255), 
	"TABLE_NAME" VARCHAR2(255), 
	"NE_KEY_NAME" VARCHAR2(255)
   ) ;

CREATE TABLE "PM_DATA_USER"."PM_DATA_FILES" 
   (	"SCHEMA" VARCHAR2(255), 
	"TABLE_NAME" VARCHAR2(255), 
	"DATETIME" TIMESTAMP (6), 
	"NE_KEY_NAME" VARCHAR2(255), 
	"NE_KEY_VALUE" VARCHAR2(255), 
	"FILE_NAME" VARCHAR2(900), 
	"DESCRIPTION" VARCHAR2(900), 
	"DATETIME_INS" TIMESTAMP (6) DEFAULT SYSDATE
   )PARTITION BY RANGE ("DATETIME"); 
  CREATE UNIQUE INDEX "PM_DATA_USER"."PM_DATA_FILES_IDX1" ON "PM_DATA_USER"."PM_DATA_FILES" ("DATETIME", "SCHEMA", "TABLE_NAME", "NE_KEY_VALUE", "FILE_NAME") ;


CREATE TABLE "PM_DATA_USER"."PM_DATA_LOADED" 
   (	"DBL_FILE" VARCHAR2(255), 
	"SCHEMA" VARCHAR2(255), 
	"TABLE_NAME" VARCHAR2(255), 
	"DATETIME" TIMESTAMP (6), 
	"NE_KEY_NAME" VARCHAR2(255), 
	"NE_KEY_VALUE" VARCHAR2(255), 
	"INSERTED_RECORDS" NUMBER(13,0), 
	"FAILED_RECORDS" NUMBER(13,0), 
	"ERROR_LOG_FILE" CLOB, 
	"DATETIME_INS" TIMESTAMP (6) DEFAULT SYSDATE, 
	"RESOLUTION" NUMBER(13,0), 
	"LOAD_TYPE" VARCHAR2(55)
   ) PARTITION BY RANGE ("DATETIME");
  CREATE INDEX "PM_DATA_USER"."PM_DATA_LOADED_IDX1" ON "PM_DATA_USER"."PM_DATA_LOADED" ("DATETIME", "SCHEMA", "TABLE_NAME", "NE_KEY_VALUE") ;

CREATE TABLE "PM_DATA_USER"."PM_DATA_QUALITY" 
   (	"SCHEMA" VARCHAR2(255), 
	"TABLE_NAME" VARCHAR2(255), 
	"DATETIME" TIMESTAMP (6), 
	"NE_KEY_NAME" VARCHAR2(900), 
	"NE_KEY_VALUE" VARCHAR2(900), 
	"COUNTER" VARCHAR2(50), 
	"VALUE" VARCHAR2(900), 
	"RULE" VARCHAR2(900), 
	"DATETIME_INS" TIMESTAMP (6) DEFAULT SYSDATE
   ) PARTITION BY RANGE ("DATETIME");
  CREATE UNIQUE INDEX "PM_DATA_USER"."PM_DATA_QUALITY_IDX1" ON "PM_DATA_USER"."PM_DATA_QUALITY" ("DATETIME", "SCHEMA", "TABLE_NAME", "NE_KEY_VALUE", "COUNTER", "RULE") ;

CREATE TABLE "PM_DATA_USER"."PM_DATA_QUALITY_CONFIG" 
   (	"SCHEMA" VARCHAR2(255), 
	"TABLE_NAME" VARCHAR2(255), 
	"NE_KEY_NAME" VARCHAR2(900), 
	"COUNTER" VARCHAR2(50), 
	"RULE" VARCHAR2(900), 
	"ACTIVE" NUMBER(2,0) DEFAULT 1, 
	"DATETIME_INS" TIMESTAMP (6) DEFAULT SYSDATE
   ) ;
  CREATE UNIQUE INDEX "PM_DATA_USER"."PM_DATA_QUALITY_CONFIG_IDX1" ON "PM_DATA_USER"."PM_DATA_QUALITY_CONFIG" ("SCHEMA", "TABLE_NAME", "COUNTER", "RULE") ;


CREATE TABLE "PM_DATA_USER"."PM_DATA_STATUS" 
   (	"DBL_FILE" VARCHAR2(255), 
	"SCHEMA" VARCHAR2(255), 
	"TABLE_NAME" VARCHAR2(255), 
	"DATETIME" TIMESTAMP (6), 
	"NE_KEY_NAME" VARCHAR2(255), 
	"NE_KEY_VALUE" VARCHAR2(255), 
	"INSERTED_RECORDS" NUMBER(13,0), 
	"AVG_INSERTED_RECORDS" NUMBER(16,3), 
	"FAILED_RECORDS" NUMBER(13,0), 
	"ERROR_LOG_FILE" CLOB, 
	"STATUS" VARCHAR2(255), 
	"DESCRIPTION" VARCHAR2(900), 
	"RESOLUTION" VARCHAR2(10), 
	"DATETIME_INS" TIMESTAMP (6) DEFAULT SYSDATE, 
	"ROOT_CAUSE_CODE" VARCHAR2(55), 
	"DATETIME_UPD_STATUS" TIMESTAMP (6) DEFAULT sysdate-(1/1440*120), 
	"DATETIME_UPD_RC" TIMESTAMP (6) DEFAULT sysdate-(1/1440*120), 
	"LOAD_TYPE" VARCHAR2(55)
   ) ;
  PARTITION BY RANGE ("DATETIME") ;
  TABLESPACE "PM_DATA_USER_DATA" 
  CREATE UNIQUE INDEX "PM_DATA_USER"."PM_DATA_STATUS_IDX1" ON "PM_DATA_USER"."PM_DATA_STATUS" ("DATETIME", "SCHEMA", "TABLE_NAME", "NE_KEY_VALUE") ;


CREATE TABLE "PM_DATA_USER"."PM_DATA_SUMMARY_LH" 
   (	"LAST_HANDLED_DATESTAMP" TIMESTAMP (6)
   );


--Add the tables to partition maintenance
insert into aircom.maintain_table (SCHEMA,TABLE_NAME,PARTRETENTION,PARTADVANCE,PARTTYPE,LASTRUNDATE,NEXTRUNDATE,SCHEDULEPERIOD,PRIORITY,MIN_DATE)
VALUES ('PM_DATA_USER','PM_DATA_FILES',3,3,1,sysdate-1,sysdate,1,1,trunc(sysdate)-3);

insert into aircom.maintain_table (SCHEMA,TABLE_NAME,PARTRETENTION,PARTADVANCE,PARTTYPE,LASTRUNDATE,NEXTRUNDATE,SCHEDULEPERIOD,PRIORITY,MIN_DATE)
VALUES ('PM_DATA_USER','PM_DATA_LOADED',3,3,1,sysdate-1,sysdate,1,1,trunc(sysdate)-3);


insert into aircom.maintain_table (SCHEMA,TABLE_NAME,PARTRETENTION,PARTADVANCE,PARTTYPE,LASTRUNDATE,NEXTRUNDATE,SCHEDULEPERIOD,PRIORITY,MIN_DATE)
VALUES ('PM_DATA_USER','PM_DATA_QUALITY',3,3,1,sysdate-1,sysdate,1,1,trunc(sysdate)-3);

insert into aircom.maintain_table (SCHEMA,TABLE_NAME,PARTRETENTION,PARTADVANCE,PARTTYPE,LASTRUNDATE,NEXTRUNDATE,SCHEDULEPERIOD,PRIORITY,MIN_DATE)
VALUES ('PM_DATA_USER','PM_DATA_STATUS',3,15,1,sysdate-1,sysdate,1,1,trunc(sysdate)-3);

commit;
